// export const technologies = [
//     //Front-end
    
//     'HTML',
//     'CSS',
//     'JavaScript',
//     'TypeScript',
//     'React',
//     'Angular',
//     'Vue',
//     'Bootstrap',
//     'Sass',
//     'Redux',
//     'GraphQL',
//     'Material UI',
//     'Tailwindcss',
//     'JQuery',
//     'Ajax',
//     'Axios',
//     'Next.js',
//     'Electron',
//     'React Native',
//     // Backend:

//     'Node.js',
//     'Express.js',
//     'Nest.js',
//     'Python',
//     'Ruby',
//     'PHP',
//     'Java',
//     'C#',
//     '.NET',
//     'ASP',
//     'Django',
//     'Flask',
//     'Ruby on Rails',
//     'Laravel',
//     'Spring Boot',
//     // Databases:
    
//     'MySQL',
//     'PostgreSQL',
//     'MongoDB',
//     'SQLite',
//     'Oracle',
//     'Microsoft SQL Server',
//     // Other Essential Technologies:
    
//     'RESTful APIs',
//     'GraphQL',
//     'Git',
//     'Webpack',
//     'Parcel',
//     'Babel',
//     'JSON',
//     'JWT',
//     'OAuth',
//     'Docker',
//     'AWS',
//     'Azure',
//     'Google Cloud',
//     'Firebase',
//     'Heroku',
//     'Postman',
//     'Kubernetes',
//     'Apache',
//     'Kafka',
//     'Web Sockets',
//     'CORS',
//     'PWA',
//     'MVC',
//     'Serverless',
//     'CI / CD',
//     'Redis',
//     'Memcached',
//     'Authentication',
//     'OAuth',
//     'Hashing',
//     'Linux',
//     // Testing
//     'Jest',
//     'Testing Library',
//     'Cypress',
//     'Enzyme',
//     'Jasmine',
//     'Mocha',

//   ];

export const technologies = {
    'Front-end': {
      'HTML': 0,
      'CSS': 0,
      'HTML5': 0,
      'CSS3': 0,
      'JavaScript': 0,
      'TypeScript': 0,
      'React': 0,
      'Angular': 0,
      'Vue': 0,
      'Bootstrap': 0,
      'Sass': 0,
      'Redux': 0,
      'Material UI': 0,
      'Tailwindcss': 0,
      'JQuery': 0,
      'Ajax': 0,
      'Axios': 0,
      'Next.js': 0,
      'Electron': 0,
      'React Native': 0,
    },
    'Backend': {
      'Node.js': 0,
      'Express.js': 0,
      'Nest.js': 0,
      'Python': 0,
      'Ruby': 0,
      'PHP': 0,
      'Java': 0,
      'C#': 0,
      '.NET': 0,
      'ASP': 0,
      'Django': 0,
      'Flask': 0,
      'Ruby on Rails': 0,
      'Laravel': 0,
      'Spring Boot': 0,
      'J2EE': 0,
    },
    'Databases': {
      'SQL': 0,
      'NoSQL': 0,
      'MySQL': 0,
      'PostgreSQL': 0,
      'MongoDB': 0,
      'SQLite': 0,
      'Oracle': 0,
      'Microsoft SQL Server': 0,
    },
    'Other Essential Technologies': {
      'RESTful APIs': 0,
      'REST': 0,
      'GraphQL': 0,
      'Git': 0,
      'Webpack': 0,
      'Parcel': 0,
      'Babel': 0,
      'JSON': 0,
      'JWT': 0,
      'OAuth': 0,
      'Docker': 0,
      'AWS': 0,
      'Azure': 0,
      'Google Cloud': 0,
      'Firebase': 0,
      'Heroku': 0,
      'Postman': 0,
      'Kubernetes': 0,
      'Apache': 0,
      'Kafka': 0,
      'Web Sockets': 0,
      'CORS': 0,
      'PWA': 0,
      'MVC': 0,
      'Serverless': 0,
      'CI / CD': 0,
      'Redis': 0,
      'Memcached': 0,
      'Authentication': 0,
      'OAuth': 0,
      'Hashing': 0,
      'Linux': 0,
      'Jira': 0,
      'Agiel': 0,
      'Scrum': 0,
      'Jenkins': 0,
      'Hibernate': 0,
    },
    'Testing': {
      'Jest': 0,
      'Testing Library': 0,
      'Cypress': 0,
      'Enzyme': 0,
      'Jasmine': 0,
      'Mocha': 0,
    },
  };
  